name: YouTube Audiobook Crawler

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup data directory
        run: |
          mkdir -p data
          touch data/crawler_data.db
          
      - name: Download previous database
        if: success()
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: crawler-data
          path: data/
          
      - name: Run crawler
        run: |
          python youtube_crawler.py \
            --min-duration 60 \
            --queries "audiobook" "full audiobook" "complete audiobook" \
            --save-interval 5 \
            --batch-size 25 \
            --max-workers 4
            
      - name: Upload database artifact
        uses: actions/upload-artifact@v3
        with:
          name: crawler-data
          path: data/crawler_data.db
          retention-days: 1
